## Broadcast Mechanism 广播机制

In [8]:
import torch

X = torch.ones(size=(8, 512, 512))
weights = torch.ones(size=(512, 512)) * 3

In [9]:
outputs = X * weights

In [10]:
outputs[0]

tensor([[3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        ...,
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.]])

In [11]:
outputs[1]

tensor([[3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        ...,
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.]])

## 广播机制在反向传播中起到的作用

In [12]:
from torch import nn

X = torch.ones(size=(8, 512, 512))
weights = nn.Parameter(torch.ones(size=(512, 512)) * 3)

outputs = X * weights
outputs = outputs.sum()
outputs.backward()

In [16]:
# 每个位置的偏导数是 8 而不是 1, 应用到了梯度累加的机制
weights.grad.data

tensor([[8., 8., 8.,  ..., 8., 8., 8.],
        [8., 8., 8.,  ..., 8., 8., 8.],
        [8., 8., 8.,  ..., 8., 8., 8.],
        ...,
        [8., 8., 8.,  ..., 8., 8., 8.],
        [8., 8., 8.,  ..., 8., 8., 8.],
        [8., 8., 8.,  ..., 8., 8., 8.]])

In [17]:
# 再尝试将 batch_size 修改为 16

X = torch.ones(size=(16, 512, 512))
weights = nn.Parameter(torch.ones(size=(512, 512)) * 3)

outputs = X * weights
outputs = outputs.sum()
outputs.backward()

weights.grad.data

tensor([[16., 16., 16.,  ..., 16., 16., 16.],
        [16., 16., 16.,  ..., 16., 16., 16.],
        [16., 16., 16.,  ..., 16., 16., 16.],
        ...,
        [16., 16., 16.,  ..., 16., 16., 16.],
        [16., 16., 16.,  ..., 16., 16., 16.],
        [16., 16., 16.,  ..., 16., 16., 16.]])