## Broadcast Mechanism 广播机制

In [50]:
import torch

X = torch.ones(size=(8, 512, 512))
weights = torch.ones(size=(512, 512)) * 3  # 不可微分的

In [51]:
outputs = X * weights
outputs.shape

torch.Size([8, 512, 512])

In [52]:
outputs[0]

tensor([[3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        ...,
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.]])

In [53]:
outputs[1]

tensor([[3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        ...,
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.]])

## 广播机制在反向传播中起到的作用

In [54]:
from torch import nn


# 666 666 | 666 666           1  1 |  1  1     8*666
# 666 666 | 666 666           1  1 |  1  1

# batch_size = 8
X = torch.ones(size=(2, 512, 512))
weights = nn.Parameter(torch.ones(size=(512, 512)) * 666)


outputs = X * weights
print(outputs.shape)
outputs = outputs.sum()
print(outputs.shape, type(outputs))
outputs.backward()

torch.Size([2, 512, 512])
torch.Size([]) <class 'torch.Tensor'>


In [55]:
# 每个位置的偏导数是 8 而不是 1, 应用到了梯度累加的机制
weights.grad.data

tensor([[2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.],
        ...,
        [2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.]])

In [56]:
# 再尝试将 batch_size 修改为 16

X = torch.ones(size=(16, 512, 512))
weights = nn.Parameter(torch.ones(size=(512, 512)) * 3)

outputs = X * weights
outputs = outputs.sum()
outputs.backward()

weights.grad.data

tensor([[16., 16., 16.,  ..., 16., 16., 16.],
        [16., 16., 16.,  ..., 16., 16., 16.],
        [16., 16., 16.,  ..., 16., 16., 16.],
        ...,
        [16., 16., 16.,  ..., 16., 16., 16.],
        [16., 16., 16.,  ..., 16., 16., 16.],
        [16., 16., 16.,  ..., 16., 16., 16.]])