## 创建一个2行5列的输入

In [13]:
import torch
from torch import nn
import torch.nn.functional as F

In [14]:
inputs = torch.tensor([i for i in range(2 * 5)], dtype=torch.float)
print(inputs.shape)
inputs = inputs.reshape(2, 5)
print(inputs.shape)

torch.Size([10])
torch.Size([2, 5])


## Sigmoid

In [15]:
torch.sigmoid(inputs)

tensor([[0.5000, 0.7311, 0.8808, 0.9526, 0.9820],
        [0.9933, 0.9975, 0.9991, 0.9997, 0.9999]])

## Softmax

In [16]:
# softmax 第一种用法; 函数的形式
# 0.0117, 0.0317, 0.0861, 0.2341, 0.6364

softmax_outputs = torch.softmax(inputs, dim=1)
print(softmax_outputs)

tensor([[0.0117, 0.0317, 0.0861, 0.2341, 0.6364],
        [0.0117, 0.0317, 0.0861, 0.2341, 0.6364]])


In [17]:
torch.sum(softmax_outputs, dim=1)

tensor([1., 1.])

In [18]:
# softmax 第二种用法; 面向对象的形式
softmax = nn.Softmax(dim=1)
softmax_outputs = softmax(inputs)
print(softmax_outputs)

tensor([[0.0117, 0.0317, 0.0861, 0.2341, 0.6364],
        [0.0117, 0.0317, 0.0861, 0.2341, 0.6364]])


In [19]:
torch.sum(softmax_outputs, dim=1)

tensor([1., 1.])

## ReLU

In [20]:
inputs

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [21]:
torch.relu(inputs)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [22]:
torch.relu(inputs * -0.1)

tensor([[-0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## GELU

In [23]:
F.gelu(inputs)

tensor([[0.0000, 0.8413, 1.9545, 2.9960, 3.9999],
        [5.0000, 6.0000, 7.0000, 8.0000, 9.0000]])

## 如果不用激活函数会怎样

看这篇文章最后的部分来理解：

[传送门](https://mp.weixin.qq.com/s/RujQDitVdhj2K7Geltwxhw)